### ISSUE TITLE
Unable to understand the all_harvardx parameter

### ISSUE THREAD

**Issue by mehulShah19** [mitodl/edx2bigquery#56]
I am trying to configure the edx2bigquery_config.py file, whereas there is one field which I am unable to understand
courses = {
    'year2': course_id_list,
    'all_harvardx': [
        "HarvardX/AI12.1x/2013_SOND",
    ],
}
Can anyone help what the **all_harvardx** field is

**Comment by ichuang** [comment]
The keys of the `courses` dict are names which can be used by the `--clist` command line option, e.g.:

    edx2bigquery --parallel --course-base-dir=SQL_DIRNAME --clist=all_harvardx doall

**Comment by mehulShah19** [comment]
Thanks @ichuang for giving this information
