### ISSUE TITLE
grades_persistent table returns raw course ids instead of their formatted versions

### ISSUE THREAD

**Issue by AbdouSeck** [mitodl/edx2bigquery#59]
The grades_persistent tables look great. Thanks, @lstmemery. However, the course_id column is coming out looking the same as the ending of the edX URL of the courses. This is not the usual format that is in the other tables. For instance, something like `course-v1:MITx+STL.162x+2T2017` should be `MITx/STL.162x/2T2017`.

I am happy to take a stab at fixing this since it should be a find-and-replace sort of thing, but I believe there is a utility function that is already getting this done. Please correct me if I am wrong. In which case, something like `"course-v1:MITx+STL.162x+2T2017".split(":")[-1].replace("+", "/")` should do.

**Comment by lstmemery** [comment]
Sorry for the oversight. Go for it!
