### ISSUE TITLE
Path Imports 

### ISSUE THREAD

**Issue by RogerTangos** [mitodl/edx2bigquery#69]
Frequently, in the code, I encounter

```from path import path```

What is the rationale for this? In Python 2.7 on OSX, this leads to an error:

```ImportError: cannot import name path```

The workaround is to simply `import path`.

Does `from path import path` work on other machines, or is this importing something outside of the standard lib? This must work for someone, but I having a hard time understanding why.

**Comment by RogerTangos** [comment]
@kunanit - this changed 6 days ago in `transfer_logs_to_gs.py`. Any insight?

**Comment by kunanit** [comment]
I noticed this import error too - see Issue #63 for why it happens.

I addressed this in PR #64

**Comment by RogerTangos** [comment]
Got it. Sorry for not seeing that sooner - I'll go ahead and checkout.
